### ISSUE TITLE
Hi question about  _MainTex in bloom

### ISSUE THREAD

**Issue by shadercoder** [keijiro/KinoBloom#7]
Hi
i have a question about _MainTex texture in bloom shader
what's the _MainTex texture format ? half-float or rgba8888? how can i retrieve this texture format

thank you
peter

**Comment by keijiro** [comment]
It depends on cases. See this line.

https://github.com/keijiro/KinoBloom/blob/master/Assets/Kino/Bloom/Bloom.cs#L180

In most cases, Default == ARGB32 and DefaultHDR = ARGBHalf.
