### ISSUE TITLE
Compilation issue with Unity 5.5

### ISSUE THREAD

**Issue by provencher** [keijiro/KinoBloom#8]
It seems one of the methods used by the script was deprecated with the 5.5 update. I don't have a screenshot of the error right now, but I'll try and produce one soon.

**Comment by keijiro** [comment]
I tested it with 5.5.0f3, but it works without any flaw. Could you let me know further info when you're available?

**Comment by provencher** [comment]
Sorry for the delay!

It seems my issue was related to an XInput DLL, and manifested in compilation errors for this script. 
I am now running on version 5.5.0p3
